# -*- coding: utf-8 -*-
"""opendataloader-1-success.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1NlnzGYqFy4A3gi3GxCYcCwDfCFrCPa
"""

# Commented out IPython magic to ensure Python compatibility.
# 挂载 Google Drive (可选)
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/pdf2markdown

import os
import subprocess

# --- 1. 安装 Java 17 (OpenJDK) ---
print("📦 Installing Java 17 via Conda...")
subprocess.run("wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh", shell=True)
subprocess.run("bash miniconda.sh -b -p /usr/local/miniconda3", shell=True)
os.environ['PATH'] = "/usr/local/miniconda3/bin:" + os.environ['PATH']
subprocess.run("conda install -y -c conda-forge openjdk=17", shell=True, stdout=subprocess.DEVNULL)

# --- 2. 安装 uv ---
print("⚡ Installing uv (Fast Python package manager)...")
subprocess.run("curl -LsSf https://astral.sh/uv/install.sh | sh", shell=True)
os.environ['PATH'] = f"/root/.cargo/bin:{os.environ['PATH']}"

# --- 3. 创建虚拟环境并安装 PyTorch (GPU Version) ---
# 使用 uv 创建 venv，并强制安装 CUDA 12.4 版本的 PyTorch
print("🏗️ Creating virtual environment with PyTorch (CUDA 12.4)...")
subprocess.run("uv venv .venv --seed", shell=True)
# 这一行是关键：确保 PyTorch 能找到 Colab 的 GPU
subprocess.run("""
source .venv/bin/activate && \
uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
""", shell=True)

# --- 4. 验证 GPU ---
print("\n✅ Verifying GPU availability:")
subprocess.run("source .venv/bin/activate && python -c 'import torch; print(f\"CUDA Available: {torch.cuda.is_available()}\"); print(f\"Device: {torch.cuda.get_device_name(0)}\")'", shell=True)

print("\n🎉 Setup complete! Please **Restart Runtime** (Runtime -> Restart Runtime) before running Cell 2.")

import os
!source .venv/bin/activate
# 使用国内清华源加速，并安装 [hybrid] 组件

!uv pip install -U opendataloader-pdf[hybrid] -i https://pypi.tuna.tsinghua.edu.cn/simple

# 验证安装
print("✅ Testing import...")
!source .venv/bin/activate

import opendataloader_pdf
print("✅ Import OK!")

from google.colab import files
import os

# 1. 上传文件
uploaded = files.upload()
if not uploaded:
    print("No file uploaded.")
    raise SystemExit

# 2. 获取文件名
pdf_name = list(uploaded.keys())[0]
base_name = os.path.splitext(pdf_name)[0]

print(f"Processing: {pdf_name}")

!source .venv/bin/activate

!opendataloader-pdf "{pdf_name}" -o ./output -f markdown,json --keep-line-breaks

output_md = f"./output/{base_name}.md"
if os.path.exists(output_md):
    print("\n" + "="*30 + " MARKDOWN OUTPUT " + "="*30)
    with open(output_md, 'r', encoding='utf-8') as f:
        content = f.read()
        print(content[:2000])  # 打印前2000字符
        if len(content) > 2000:
            print("\n... (truncated)")
else:
    print("❌ Conversion failed or file not found.")

# @title 📥 4. 下载转换结果

import shutil
from google.colab import files

# 打包输出文件夹
archive_name = "converted_pdfs"
shutil.make_archive(archive_name, 'zip', './output')

# 触发下载
files.download(f'{archive_name}.zip')
print("✅ Download started!")

"""以上成功执行！！！"""

# @title 🧠 5. [Optional] Hybrid Mode for Scanned PDFs

# 后台启动 Hybrid Backend (Docling Serve)
# 注意：Colab 可能会在长时间无操作后断开连接
print("Starting Hybrid Backend (CPU mode)... This may take a few minutes.")
print("Keep this cell running while processing.")

!source .venv/bin/activate && \
nohup opendataloader-pdf-hybrid --port 5002 > hybrid.log 2>&1 &

print("Backend started. Check status with: !ps aux | grep opendataloader")























